receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlphttp/backend:
    endpoint: "http://backend:5000"
    encoding: json
    compression: none
  otlphttp/dynatrace:
    endpoint: "${env:DYNATRACE_API_URL}/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${env:DYNATRACE_API_TOKEN}"
  logging:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/backend, otlphttp/dynatrace, logging]
